#!/bin/bash
WORKDIR=$HOME/.doit
NOTEFILE=$WORKDIR/notes.txt
DONEITFILE=$WORKDIR/doneit.txt

if [ ! -d "$WORKDIR" ]; then
  mkdir $WORKDIR
fi

if [ ! -f $NOTEFILE ]; then
  touch $NOTEFILE
fi

if [ ! -f $DONEITFILE ]; then
  touch $DONEITFILE
fi

while getopts ":h" opt; do
  case ${opt} in
    h )
      echo "Usage:"
      echo "    doit add <todo>                      Adds things to do to  a list with an ID."
      echo "    doit list                            Lists all things to do."
      echo "    doit complete <id>                   Removes the note with the specified ID from the list."
      echo "    doit done                            List completed things to do."
      exit 0
      ;;
   \? )
     echo "Invalid Option: -$OPTARG" 1>&2
     exit 1
     ;;
  esac
done
shift $((OPTIND -1))

subcommand=$1; shift
case "$subcommand" in
  add)
    COUNT=$WORKDIR/count.txt
    if [ ! -f $COUNT ]; then
      echo "0" > $COUNT
    fi

    read -r current_count < $COUNT
    next_count=$((current_count + 1))
    echo "$next_count" > $COUNT

    echo "$next_count $1" >> $NOTEFILE
    echo "doit: $1"; 
    ;;
  list)
    cat $NOTEFILE
    ;;
  complete)
    TARGET=`grep "^$1" $NOTEFILE`
    read -p "Complete doit: $TARGET? [y/N]" confirmation
    if [[ "$confirmation" == "y" ]]; then
      AFTER_REMOVE=`sed "/^$TARGET/ d" < $NOTEFILE`
      echo $AFTER_REMOVE > $NOTEFILE
      DATE=`date "+%Y-%m-%d %H:%M:%S"`
      echo "Date: $DATE" >> $DONEITFILE
      echo $TARGET >> $DONEITFILE
      echo "" >> $DONEITFILE
      echo "Completed: $1"
    fi
    ;;
  done)
    cat $DONEITFILE
    ;;
esac
